# 6시 51분 ~
# - 식품 정보(FOOD_PRODUCT)
# RRODUCT_ID, PRODUCT_NAME, PRODUCT_CD(식품코드), CATEGORY(식품분류), PRICE

# - 주문 정보(FOOD_ORDER)
# ORDER_ID, PRODUCT_ID, AMOUNT, PRODUCE_DATE(생산일), IN_DATE(입고일), OUT_DATE(출고일), FACTORY_ID, WAREHOUSE_ID

SELECT P.PRODUCT_ID 'PRODUCT_ID', P.PRODUCT_NAME 'PRODUCT_NAME', P.PRICE*AMOUNT 'TOTAL_SALES'
FROM FOOD_PRODUCT P
RIGHT JOIN (
            SELECT PRODUCT_ID, SUM(O.AMOUNT) 'AMOUNT'
            FROM FOOD_ORDER O 
            WHERE DATE_FORMAT(O.PRODUCE_DATE, "%Y-%m") = '2022-05'
            GROUP BY O.PRODUCT_ID
            ) I
ON P.PRODUCT_ID = I.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC
;
