SELECT USB.TITLE, USB.BOARD_ID, UGR.REPLY_ID, UGR.WRITER_ID, UGR.CONTENTS, DATE_FORMAT(UGR.CREATED_DATE, '%Y-%m-%d') 'CREATED_DATE'
FROM USED_GOODS_BOARD USB JOIN USED_GOODS_REPLY UGR
ON USB.BOARD_ID = UGR.BOARD_ID
WHERE DATE_FORMAT(USB.CREATED_DATE, "%Y-%m")='2022-10'
ORDER BY UGR.CREATED_DATE, USB.TITLE